#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x11968C44928CAEFC (bhush94@gmail.com)
#
Name     : kwrited
Version  : 5.14.2
Release  : 6
URL      : https://download.kde.org/stable/plasma/5.14.2/kwrited-5.14.2.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.14.2/kwrited-5.14.2.tar.xz
Source99 : https://download.kde.org/stable/plasma/5.14.2/kwrited-5.14.2.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: kwrited-bin = %{version}-%{release}
Requires: kwrited-data = %{version}-%{release}
Requires: kwrited-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde

%description
No detailed description available

%package bin
Summary: bin components for the kwrited package.
Group: Binaries
Requires: kwrited-data = %{version}-%{release}
Requires: kwrited-license = %{version}-%{release}

%description bin
bin components for the kwrited package.


%package data
Summary: data components for the kwrited package.
Group: Data

%description data
data components for the kwrited package.


%package license
Summary: license components for the kwrited package.
Group: Default

%description license
license components for the kwrited package.


%prep
%setup -q -n kwrited-5.14.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540470398
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1540470398
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kwrited
cp COPYING %{buildroot}/usr/share/package-licenses/kwrited/COPYING
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kwrited

%files data
%defattr(-,root,root,-)
/usr/share/knotifications5/kwrited.notifyrc
/usr/share/xdg/autostart/kwrited-autostart.desktop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kwrited/COPYING
